### ISSUE TITLE
Self-Hosting PrintWatch Server

### ISSUE THREAD

**Issue by Archmonger** [printpal-io/OctoPrint-PrintWatch#10]
It would be nice to self-host a PrintWatch server, similar to TheSpaghettiDetective.

Would be extra amazing if it was a Docker within Unraid Community Applications.

**Comment by printpal-io** [comment]
> It would be nice to self-host a PrintWatch server, similar to TheSpaghettiDetective.

We are finishing development and testing of a locally-run version of the software. It is designed to be able to run on a Raspberry Pi. It is however primarily geared for CUDA enabled devices. Our recent development results are promising, however it may be a little overkill to run unless you have multiple printers being monitored.

**Comment by Archmonger** [comment]
At least in my scenario, I would be hosting it on a local Unraid server.

So it would be most convenient for me if it was dockerized and listed on the Unraid Community Applications store.

**Comment by mizz141** [comment]
+1 for this, currently hosting TSD on unraid, but it's become a bit of a hassle keeping everything running as it should (even with scripts for updating it.) Even better if the collected data would be useful in advancing the software, which currently is not possible with TSD.

**Comment by olav-valle** [comment]
+1 on this. We are currently working on developing our the software solution of our printer farm control system in a project here at the Norwegian University of Science and Technology (NTNU), and we've been researching the possibilities of running ML based supervision as part of it. Sadly, the pricing of this service, and others of its kind, is simply outside the project's budget, and so we're more interested in open source and self-hosted solutions. We would be very interested in contributing towards the development and testing of self-hosted solutions, if we end up pursuing that part of the project.

**Comment by printpal-io** [comment]
> +1 on this. We are currently working on developing our the software solution of our printer farm control system in a project here at the Norwegian University of Science and Technology (NTNU), and we've been researching the possibilities of running ML based supervision as part of it. Sadly, the pricing of this service, and others of its kind, is simply outside the project's budget, and so we're more interested in open source and self-hosted solutions. We would be very interested in contributing towards the development and testing of self-hosted solutions, if we end up pursuing that part of the project.

We do offer a student discount in addition to simply working with students collaboratively. Please reach out to me by email at lebiedzinskip@printpal.io and we can discuss your project.

**Comment by Starker3** [comment]
+1 on this. I'd also have it hosted on an Unraid box which has a GPU.

**Comment by printpal-io** [comment]
Added as a work item. Closing Item.

**Comment by Archmonger** [comment]
Just a heads up so you're aware, the Unraid community has been long looking for a TSD alternative that has a community app store listing. Right now, setting up TSD on Unraid is super inconvenient.

You'd definitely get a good boost in popularity if you do this. And I registering this repo with [GitHub Sponsors](https://github.com/sponsors) prior to that.

See https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/245 for more info on TSD's perspective.
