### ISSUE TITLE
Printwatch is viewing video upside down 

### ISSUE THREAD

**Issue by jonathanalevi** [printpal-io/OctoPrint-PrintWatch#12]
Octoprint allows rotation of the video, so some people choose to put their camera upside down. 
Printwatch unfortunately doesn't have an option to flip the video, so it's watching upside down:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/1540530/155553729-9da2123c-6fbf-4db8-ac27-74707ed05f59.png">

**Comment by plebbyd** [comment]
> Octoprint allows rotation of the video, so some people choose to put their camera upside down. Printwatch unfortunately doesn't have an option to flip the video, so it's watching upside down:
> 
> <img alt="image" width="816" src="https://user-images.githubusercontent.com/1540530/155553729-9da2123c-6fbf-4db8-ac27-74707ed05f59.png">

For the Machine Learning object detection model, this is irrelevant, it will detect defects the same no matter how to camera is augmented. 

This is more of a user experience issue in the Preview tab. Would you like me to create a work item to allow users to flip the preview frame?

**Comment by jonathanalevi** [comment]
Hmm, I would have assumed that this would "throw off" the machine learning, as it would have to detect more possible variations of how spaghetti looks, rather than just realizing that spaghetti is always top to bottom (for example, imagine if the user rotates the camera 90 degrees, suddenly spaghetti is right to left). More instances to learn. In any case, yeah, it would be good to flip the preview frame, and I'd _think_ it would be good to inform the machine learning model, but you'd know better than I (who know nothing about machine learning whatsoever) 

thanks
