### ISSUE TITLE
Update failed, no user Interface on Screen at Printer but connection is up...

### ISSUE THREAD

**Issue by andre301283** [printpal-io/OctoPrint-PrintWatch#22]
Since the last update something went wrong with my octopi... i don´t know what to do to get it up and running again. please help.... here is the log...

Aktualisiere gerade, bitte warten.

++++++++++++++++++++++++++++++++++
Aktualisiere printwatch auf 1.3.01
++++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/printpal-io/OctoPrint-PrintWatch/archive/1.3.01.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/printpal-io/OctoPrint-PrintWatch/archive/1.3.01.zip
Downloading https://github.com/printpal-io/OctoPrint-PrintWatch/archive/1.3.01.zip (105 bytes)
ERROR: Exception:
Traceback (most recent call last):
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
status = self.run(options, args)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
return func(self, options, args)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 321, in run
reqs, check_supported_wheels=not options.target_dir
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
requirements, max_rounds=try_to_avoid_resolution_too_deep,
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
name, crit = self._merge_into_criterion(r, parent=None)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
name = self._p.identify(requirement)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
return dependency.name
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
return self.candidate.name
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
return self.project_name
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
self._name = canonicalize_name(self.dist.project_name)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
self._prepare()
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
dist = self._prepare_distribution()
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
self._ireq, parallel_builds=True,
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 505, in _prepare_linked_requirement
self.download_dir, hashes,
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 263, in unpack_url
unpack_file(file.path, location, file.content_type)
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/utils/unpacking.py", line 261, in unpack_file
flatten=not filename.endswith('.whl')
File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/utils/unpacking.py", line 129, in unzip_file
zip = zipfile.ZipFile(zipfp, allowZip64=True)
File "/usr/lib/python3.7/zipfile.py", line 1222, in __init__
self._RealGetContents()
File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Die Aktualisierung wurde nicht erfolgreich abgeschlossen. Bitte konsultiere <code>octoprint.log</code> und <code>plugin_softwareupdate_console.log</code> für Details.

Thanks for advice...
Andre

**Comment by printpal-io** [comment]
> Since the last update something went wrong with my octopi... i don´t know what to do to get it up and running again. please help.... here is the log...
> 
> Aktualisiere gerade, bitte warten.
> 
> ++++++++++++++++++++++++++++++++++ Aktualisiere printwatch auf 1.3.01 ++++++++++++++++++++++++++++++++++ /home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/printpal-io/OctoPrint-PrintWatch/archive/1.3.01.zip --no-cache-dir Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple Collecting https://github.com/printpal-io/OctoPrint-PrintWatch/archive/1.3.01.zip Downloading https://github.com/printpal-io/OctoPrint-PrintWatch/archive/1.3.01.zip (105 bytes) ERROR: Exception: Traceback (most recent call last): File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main status = self.run(options, args) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper return func(self, options, args) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 321, in run reqs, check_supported_wheels=not options.target_dir File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve requirements, max_rounds=try_to_avoid_resolution_too_deep, File "/home/pi/oprint/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve state = resolution.resolve(requirements, max_rounds=max_rounds) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve name, crit = self._merge_into_criterion(r, parent=None) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion name = self._p.identify(requirement) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify return dependency.name File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name return self.candidate.name File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name return self.project_name File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name self._name = canonicalize_name(self.dist.project_name) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist self._prepare() File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare dist = self._prepare_distribution() File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution self._ireq, parallel_builds=True, File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement return self._prepare_linked_requirement(req, parallel_builds) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 505, in _prepare_linked_requirement self.download_dir, hashes, File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 263, in unpack_url unpack_file(file.path, location, file.content_type) File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/utils/unpacking.py", line 261, in unpack_file flatten=not filename.endswith('.whl') File "/home/pi/oprint/lib/python3.7/site-packages/pip/_internal/utils/unpacking.py", line 129, in unzip_file zip = zipfile.ZipFile(zipfp, allowZip64=True) File "/usr/lib/python3.7/zipfile.py", line 1222, in **init** self._RealGetContents() File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> 
> Die Aktualisierung wurde nicht erfolgreich abgeschlossen. Bitte konsultiere `octoprint.log` und `plugin_softwareupdate_console.log` für Details.
> 
> Thanks for advice... Andre

This appears to be an issue with the PluginManager and not the plugin itself. Try installing the Plugin "via URL" in the PluginManager using this link: https://github.com/printpal-io/OctoPrint-Printwatch/archive/master.zip

Let me know if that works.

**Comment by andre301283** [comment]
Tanks for answering. I already tried to uodate via console but im getting exact same error.

i dint think its what u mean cause emediately at same time the octoscreen plug8n stopoed working. the funny thin is the printer is up an running fine in web browser i cann access everything printing is possible... 
but the octoscreen is stuck at connecting screen with message: Printer is offline.... then Loading..... forever tries to connect. 

if i click on System to shut it down the pi its stuck too and reboots to the same sreen... 

Something went wrong during install of the official updates via webserver last time i remember. i didnt change anything on this built..

id like to try to repair this... thanks 
![20231004_175638](https://github.com/printpal-io/OctoPrint-PrintWatch/assets/97801958/338e73e4-083e-46ea-a4a8-55055d229c0f)

**Comment by printpal-io** [comment]
IF you could send me your octoprint.log file From Settings > Logging > octoprint.log I can take a look at it. Please join our official discord channel and send it to me there: https://discord.gg/DRM7w88AbS

**Comment by andre301283** [comment]
Update... found failure of octoscreen... .api key and ip changed randomly... up an running again...

the file is here i already posted it.... read the line with "bad zip file".... how does that come? still not able to install update either via plugin manager or console.... what´s wrong?

<a href='https://postimg.cc/p5CbLFvx' target='_blank'><img src='https://i.postimg.cc/p5CbLFvx/Screenshot-2023-10-06-2020201.png' border='0' alt='Screenshot-2023-10-06-2020201'/></a>

**Comment by andre301283** [comment]
....thanks @printpal-io i got u wrong... i insatlled update manually wie plugin manager with the url... gonna close the case... thx

**Comment by andre301283** [comment]
....thanks @printpal-io i got u wrong... i insatlled update manually via plugin manager with the url... gonna close the case... thx
